name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_FILE_PATH: HelloWorld.vcxproj
  BUILD_CONFIGURATION: Debug|x64 
  DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe
  QT_PATH: ${{ github.workspace }}\ThirdParty\Qt\6.6.1\msvc2019_64
  QT_VERSION: 6.6.1
  
permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2


        
    - name: Debug - List repository files
      run: dir /s
      shell: cmd


   # Step 10: Download Qt Visual Studio Tools Extension
    - name: Download Qt Visual Studio Tools Extension
      run: |
        Invoke-WebRequest -Uri "https://mirror.netcologne.de/qtproject/development_releases/vsaddin/2.8.0/qt-vsaddin-msvc2022-2.8.0.vsix" -OutFile "qt-vsaddin.vsix"
      shell: powershell
      
    # Step 11: Install Qt Visual Studio Tools Extension
    - name: Install Qt Visual Studio Tools Extension
      run: |
        $vsPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
        $vsInstallerPath = &"$vsPath\Common7\IDE\CommonExtensions\Microsoft\VsixInstaller\vsixinstaller.exe"
        if (!(Test-Path -Path $vsInstallerPath)) {
          $vsInstallerPath = &"$vsPath\VsixInstaller.exe"
        }
        &"$vsInstallerPath" -quiet -a -s -q qt-vsaddin.vsix
      shell: powershell

      
    # Step 12: Set Qt Path in Visual Studio
    - name: Set Qt Path in Visual Studio
      run: |
        $vsPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
        &"$vsPath\Common7\IDE\devenv.com" /command "Tools.Options"
        &"$vsPath\Common7\IDE\devenv.com" /command "QtVersions.AddQtVersion"
        &"$vsPath\Common7\IDE\devenv.com" /command "qtAddExistingVersion ${{ env.QT_PATH }}"
      shell: powershell

      
    - name: Build
      shell: cmd
      run: |
        "%DEVENV_PATH%" "%PROJECT_FILE_PATH%" /Build "%BUILD_CONFIGURATION%" /Out buildLog_Debug.txt
