name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_FILE_PATH: HelloWorld.vcxproj
  BUILD_CONFIGURATION: Debug|x64 
  SOLUTION_FILE_PATH: HelloWorld.sln
  DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
  QT_VERSION: 6.6.1
  DEVENV_PATH2: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
  QT_PATH: ${{ github.workspace }}\ThirdParty\Qt\6.6.1\msvc2019_64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2




# Step: Download and install Qt VS add-in
    - name: Download Qt VS add-in
      run: curl -L -o qt-vsaddin-msvc2022-3.0.2.vsix https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix
      shell: cmd

    - name: Debug - Locate vsixinstaller.exe
      run: |
        echo "Locating vsixinstaller.exe..."
        for /r "C:\Program Files (x86)\Microsoft Visual Studio" %%F in (vsixinstaller.exe) do @echo %%F
      shell: cmd

    - name: Install Qt VS add-in
      run: |
        for /r "C:\Program Files (x86)\Microsoft Visual Studio" %%F in (vsixinstaller.exe) do (
          call "%%F" /quiet qt-vsaddin-msvc2022-3.0.2.vsix
          exit /b 0
        )
        echo "VSIX Installer not found"
        exit /b 1
      shell: cmd

    # Step: Set Qt version in Visual Studio
    - name: Set Qt version in Visual Studio
      run: |
        "%DEVENV_PATH2%" /command "Qt5.QtOptions.QtVersions.AddVersion?Name=6.6.1&Path=%QT_PATH%"
      shell: cmd











      
    - name: Build with devenv.com
      shell: cmd
      run: |
        "%DEVENV_PATH%" "%PROJECT_FILE_PATH%" /Build "%BUILD_CONFIGURATION%" /Out buildLog_Debug.txt
