name: MSBuild

on:
  push:
    branches: [ "Demo" ]
  pull_request:
    branches: [ "Demo" ]

env:
  QT_VERSION: 6.6.1
  QT_PATH: ${{ github.workspace }}\Qt\6.6.1\msvc2019_64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Download Qt VS add-in
      run: |
        curl -L -o qt-vsaddin-msvc2022-3.0.2.vsix https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix
      shell: cmd

    - name: Install Qt VS add-in
      run: |
        Start-Process "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\vsixinstaller.exe" -ArgumentList "/quiet", "qt-vsaddin-msvc2022-3.0.2.vsix" -Wait -PassThru
      shell: pwsh

    - name: Set Qt version in Visual Studio
      run: |
        $devenvPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com"
        $qtPath = "${{ github.workspace }}\Qt\6.6.1\msvc2019_64"
        $command = "`"$devenvPath`" /command `"Qt5.QtOptions.QtVersions.AddVersion?Name=6.6.1&Path=$qtPath`""
        Write-Output "Running command: $command"
        & "$devenvPath" /command "Qt5.QtOptions.QtVersions.AddVersion?Name=6.6.1&Path=$qtPath" 2>&1 | Tee-Object -FilePath qt_version_log.txt
        Write-Output "Qt version log:"
        Get-Content -Path qt_version_log.txt
      shell: pwsh
