name: Build and Test

on: [push, pull_request]

env:
  QT_DIR: C:\Qt\5.15.2\mingw81_64
  MINGW_DIR: C:\Qt\Tools\mingw81_64

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Qt
      run: choco install qt5-default --params "/InstallDir:C:\Qt"

    - name: Install MinGW
      run: choco install mingw --version=8.1.0

    - name: Set Qt and MinGW environment variables
      shell: powershell
      run: |
        echo "$env:QT_DIR\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "$env:QT_DIR\lib" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "$env:QT_DIR\include" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "$env:MINGW_DIR\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        [Environment]::SetEnvironmentVariable('QTDIR', '$env:QT_DIR', 'Machine')
        [Environment]::SetEnvironmentVariable('MINGW_DIR', '$env:MINGW_DIR', 'Machine')
        [Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';$env:QT_DIR\bin;$env:MINGW_DIR\bin', 'Machine')

    - name: Refresh environment variables
      shell: powershell
      run: refreshenv

    - name: Verify Qt and MinGW installation and paths
      run: |
        echo %QTDIR%
        echo %MINGW_DIR%
        echo %PATH%
        dir %QTDIR%
        dir %MINGW_DIR%

    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Configure CMake with MinGW
      run: cmake -B build -S . -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=%QTDIR% -DCMAKE_CXX_COMPILER=%MINGW_DIR%\bin\g++.exe -DCMAKE_C_COMPILER=%MINGW_DIR%\bin\gcc.exe

    - name: Build with CMake
      run: cmake --build build --config Debug
