name: Build Qt C++ Project

on:
  push:
    branches:
      - m
  pull_request:
    branches:
      - m

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Verify Qt Installation
      run: |
        echo "Verifying Qt installation"
        dir ${{ env.Qt5_15_2_dir }}

    - name: Build Project
      env:
        QT_DIR: ${{ env.QT_BASE }}/5.15.2/msvc2019_64
      run: |
        $env:Path += ";${{ env.QT_DIR }}\bin"
        devenv.exe <your_solution_file>.sln /Build "Release"
