name: Qt VS Add-in Setup (Windows)

on:
  push: # Trigger the workflow on pushes

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Checkout the repository code

      - name: Setup MSBuild and Visual Studio
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '17.0' # Visual Studio 2022

      - name: Download Qt VS Add-in (version 3.0.2)
        run: |
          echo "Downloading Qt VS Add-in..."
          curl -L -o qt-vsaddin-msvc2022-3.0.2.vsix https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix

      - name: Install Qt VS Add-in
        shell: powershell
        run: |
          echo "Installing Qt VS Add-in..."
          $vsixInstallerPath = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vsixinstaller.exe"
          if (-not (Test-Path $vsixInstallerPath)) {
            throw "vsixinstaller.exe not found at $vsixInstallerPath."
          }
          Start-Process -FilePath $vsixInstallerPath -ArgumentList 'qt-vsaddin-msvc2022-3.0.2.vsix', '/quiet', '/norestart' -NoNewWindow -Wait

      - name: Verify Installation
        shell: powershell
        run: |
          echo "Verifying Qt VS Add-in installation..."
          Get-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\VisualStudio\\Setup\\Instances\\*' | Select-Object -ExpandProperty InstallationPath | ForEach-Object { & "$_\Common7\IDE\devenv.exe" /setup }
