name: Qt VS Add-in Setup (Windows)

on:
  push: # Trigger the workflow on pushes

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Checkout the repository code

      - name: Install Visual Studio Build Tools
        uses: microsoft/windows-update@v1.1
        with:
          updates: 'BuildTools-2022'

      - name: Install Visual Studio 2022 C++ Desktop workload
        shell: powershell
        run: |
          Install-Product -Name VisualStudio.Desktop.Cpp.Workload -IncludeRecommended -Wait -Source https://visualstudio.microsoft.com/downloads/

      - name: Download Qt VS Add-in (version 3.0.2)
        run: |
          echo Downloading Qt VS Add-in...
          curl -L -o qt-vsaddin-msvc2022-3.0.2.vsix https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix

      - name: Install Qt VS Add-in
        run: |
          echo Installing Qt VS Add-in...
          start /wait vsixinstaller.exe /quiet /install qt-vsaddin-msvc2022-3.0.2.vsix

      - name: Verify Installation
        run: |
          echo Verifying Qt VS Add-in installation...
          powershell -Command "Get-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\VisualStudio\\Setup\\Instances\\*' | Select-Object -ExpandProperty InstallationPath | % { & \"$_\Common7\IDE\devenv.exe\" /setup }"
