name: Build with CMake and Visual Studio

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  QT_VERSION: 6.6.1
  QT_PATH: ${{ github.workspace }}\\Qt\\6.6.1\\msvc2019_64
  DEVENV_PATH: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.com"

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Git
      run: choco install git -y
      shell: powershell

    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
      shell: powershell

    - name: Install 7zip
      run: choco install 7zip -y
      shell: powershell

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Download Qt
      run: |
        mkdir $env:GITHUB_WORKSPACE\\Qt
        Invoke-WebRequest -Uri http://download.qt.io/official_releases/qt/6.6/6.6.1/qt-opensource-windows-x86-6.6.1.7z -OutFile $env:GITHUB_WORKSPACE\\qt.7z
        7z x $env:GITHUB_WORKSPACE\\qt.7z -o$env:GITHUB_WORKSPACE\\Qt
      shell: powershell

    - name: Configure CMake
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH=$env:QT_PATH
      shell: powershell

    - name: Build with devenv.com
      run: |
        $env:DEVENV_PATH = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.com"
        & $env:DEVENV_PATH build\\YOUR_SOLUTION.sln /Build Release
      shell: powershell

    - name: Add Qt version in Visual Studio
      run: |
        $env:QT_VERSION = "6.6.1"
        $env:QT_PATH = "${{ github.workspace }}\\Qt\\6.6.1\\msvc2019_64"
        $env:DEVENV_PATH2 = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.com"
        & $env:DEVENV_PATH2 /command "Qt5.QtOptions.QtVersions.AddVersion?Name=Qt-$env:QT_VERSION-msvc2019_64&Path=$env:QT_PATH"
      shell: pwsh

    - name: Set Qt version in Visual Studio
      run: |
        $env:QT_VERSION = "6.6.1"
        $env:QT_PATH = "${{ github.workspace }}\\Qt\\6.6.1\\msvc2019_64"
        $env:DEVENV_PATH2 = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.com"
        & $env:DEVENV_PATH2 /command "Qt5.QtOptions.QtDefaultVersion?Name=Qt-$env:QT_VERSION-msvc2019_64"
      shell: pwsh
