name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_FILE_PATH: HelloWorld.vcxproj
  BUILD_CONFIGURATION: Debug|x64 
  SOLUTION_FILE_PATH: HelloWorld.sln
  DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
  QT_VERSION: 6.6.1

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2


    - name: Install Qt Visual Studio Tools Extension
      run: |
        powershell -Command "& {Start-Process -Wait 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe' -ArgumentList 'modify', '--installPath', 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise', '--add', 'Component.ID', '--quiet'}"

    - name: Configure Qt Version
      run: |
        $qtVersionName = "6.6.1"
        $qtPath = "${{ github.workspace }}\ThirdParty\Qt\6.6.1\msvc2019_64"
        $devenvPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com"
        
        Write-Output "Adding Qt version $qtVersionName at path $qtPath using $devenvPath"
        
        $addQtVersionCmd = "& `$devenvPath -Command `"Qt5VSAddin.QtVersionManager.AddQtVersion(`'$qtPath`', `'$qtVersionName`')`""
        Write-Output "Running command: $addQtVersionCmd"
        
        Invoke-Expression $addQtVersionCmd | Out-File qt_add_output.log -Append
        Get-Content qt_add_output.log


    - name: Build with devenv.com
      run: |
        echo "Current directory: $(Get-Location)"
        & "${{ env.DEVENV_PATH }}" ${{ env.SOLUTION_FILE_PATH }} /Build "${{ env.BUILD_CONFIGURATION }}" /Out buildLog_Debug.txt
      shell: pwsh
