name: CI

on: [push, pull_request]

env:
  QT_VERSION: 6.6.1
  DEVENV_PATH2: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.com"
  QT_PATH: ${{ github.workspace }}\\Qt\\6.6.1\\msvc2019_64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Download Qt VS add-in
      run: |
        curl -L -o qt-vsaddin-msvc2022-3.0.2.vsix https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix
      shell: cmd

    - name: Install Qt VS add-in
      run: |
        $vsixPath = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\VSIXInstaller.exe"
        $vsixInstallerArguments = '/quiet', '/logFile:vsixinstall.log', 'qt-vsaddin-msvc2022-3.0.2.vsix'
        Write-Output "Installing Qt VS add-in..."
        Start-Process -FilePath $vsixPath -ArgumentList $vsixInstallerArguments -NoNewWindow -Wait -PassThru
        $exitCode = $?
        Write-Output "VSIX Installer exited with code $exitCode"
        if ($exitCode -ne 0) {
          Write-Error "VSIX Installer failed. Check the log file for details."
          exit $exitCode
        }
      shell: pwsh

    - name: Add Qt version in Visual Studio
      run: |
        $env:QT_VERSION = "6.6.1"
        $env:QT_PATH = "${{ github.workspace }}\\Qt\\6.6.1\\msvc2019_64"
        $env:DEVENV_PATH2 = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.com"
        & $env:DEVENV_PATH2 /command "Qt5.QtOptions.QtVersions.AddVersion?Name=Qt-$env:QT_VERSION-msvc2019_64&Path=$env:QT_PATH"
      shell: pwsh

    - name: Set Qt version in Visual Studio
      run: |
        $env:QT_VERSION = "6.6.1"
        $env:QT_PATH = "${{ github.workspace }}\\Qt\\6.6.1\\msvc2019_64"
        $env:DEVENV_PATH2 = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.com"
        & $env:DEVENV_PATH2 /command "Qt5.QtOptions.QtDefaultVersion?Name=Qt-$env:QT_VERSION-msvc2019_64"
      shell: pwsh

    - name: Upload VSIX Installer Log
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: vsixinstall-log
        path: vsixinstall.log
