name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_FILE_PATH: HelloWorld.vcxproj
  BUILD_CONFIGURATION: Debug|x64 
  SOLUTION_FILE_PATH: HelloWorld.sln
  DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
  QT_VERSION: 6.6.1

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install Qt Visual Studio Tools Extension
      run: |
        powershell -Command "& {Start-Process 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Microsoft\VsixInstaller.exe' -ArgumentList '/quiet', '/a', '/logFile=install_log.txt', 'https://marketplace.visualstudio.com/_apis/public/gallery/publishers/qtproject/vsextensions/vs-tools/2.4.2/vspackage'}"

    - name: Configure Qt Version
      run: |
        $qtVersionName = "6.6.1"
        $qtPath = "${{ github.workspace }}\ThirdParty\Qt\6.6.1\msvc2019_64"
        $configFilePath = [System.IO.Path]::Combine($env:APPDATA, "QtProject", "qtversion.xml")

        if (-Not (Test-Path $configFilePath)) {
          New-Item -ItemType File -Path $configFilePath
        }

        $xmlContent = [xml](Get-Content $configFilePath)
        $root = $xmlContent.CreateElement("QtConfiguration")
        $version = $xmlContent.CreateElement("QtVersion")
        $version.SetAttribute("Id", $qtVersionName)
        $version.SetAttribute("Path", $qtPath)
        $root.AppendChild($version)
        $xmlContent.AppendChild($root)
        $xmlContent.Save($configFilePath)

    - name: Build with devenv.com
      run: |
        echo "Current directory: $(Get-Location)"
        & "${{ env.DEVENV_PATH }}" ${{ env.SOLUTION_FILE_PATH }} /Build "${{ env.BUILD_CONFIGURATION }}" /Out buildLog_Debug.txt
      shell: pwsh
