name: Build Qt C++ Project

on:
  push:
    branches:
      - m
  pull_request:
    branches:
      - m

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; `
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Qt
      run: |
        choco install qtcreator -y
        choco install qt5-default -y

    - name: Install Qt Visual Studio Tools
      run: |
        Invoke-WebRequest -Uri "https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix" -OutFile "qt-vsaddin-msvc2022.vsix"
        & "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VSIXInstaller.exe" qt-vsaddin-msvc2022.vsix

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Verify Qt Installation
      run: |
        echo "Verifying Qt installation"
        dir "C:\Qt"

    - name: Build Project
      env:
        QT_DIR: C:\Qt\5.15.2\msvc2019_64
      run: |
        $env:Path += ";${{ env.QT_DIR }}\bin"
        devenv.exe <your_solution_file>.sln /Build "Release"
