name: Build Qt C++ Project

on:
  push:
    branches:
      - m
  pull_request:
    branches:
      - m

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtcharts qtwebengine'
        archives: 'qtbase qtsvg'
        set-env: 'true'

    - name: Install Qt Visual Studio Tools
      run: |
        Invoke-WebRequest -Uri "https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix" -OutFile "qt-vsaddin-msvc2022.vsix"
        Start-Process -Wait -FilePath "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VSIXInstaller.exe" -ArgumentList "qt-vsaddin-msvc2022.vsix"

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Verify Qt Installation
      run: |
        echo "Verifying Qt installation"
        dir "${{ env.QT_ROOT }}/msvc2019_64"

    - name: Build Project
      env:
        QT_DIR: ${{ env.QT_ROOT }}/msvc2019_64
      run: |
        $env:Path += ";${{ env.QT_DIR }}\bin"
        devenv.exe <your_solution_file>.sln /Build "Release"
