name: Build and Test

on: [push, pull_request]

env:
  PROJECT_FILE_PATH: HelloWorld.vcxproj
  BUILD_CONFIGURATION: Debug|x64 
  DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: m

    - name: Set up Qt
      run: |
        choco install qt5-default
        echo "C:\Qt\5.15.2\msvc2019_64\bin" >> $env:GITHUB_PATH

    - name: Build with Visual Studio
      shell: cmd
      run: |
        "%DEVENV_PATH%" "%PROJECT_FILE_PATH%" /Build "%BUILD_CONFIGURATION%"
