name: Build HelloWorld Qt Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: |
          qtbase
          qttools

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure Environment
      run: |
        echo "QTDIR=${{ env.QT_INSTALL_DIR }}" >> $GITHUB_ENV
        echo "QMAKESPEC=win32-msvc" >> $GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=${{ env.QT_INSTALL_DIR }}" >> $GITHUB_ENV
        echo "${{ env.QT_INSTALL_DIR }}\\bin" >> $GITHUB_PATH

    - name: Update project file with Qt paths
      run: |
        sed -i 's|\$(QTDIR)|${{ env.QT_INSTALL_DIR }}|g' HelloWorld.vcxproj

    - name: Build the solution
      run: |
        msbuild HelloWorldProject.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: hello-world-build
        path: |
          Release
