name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  QT_VERSION: 6.6.1
  DEVENV_PATH2: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
  QT_PATH: ${{ github.workspace }}\Qt\6.6.1\msvc2019_64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Download Qt VS add-in
      run: |
        curl -L -o qt-vsaddin-msvc2022-3.0.2.vsix https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix
      shell: cmd

    - name: Print Visual Studio IDE Directory
      run: |
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE"
      shell: cmd

    - name: Install Qt VS add-in
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\vsixinstaller.exe" /quiet qt-vsaddin-msvc2022-3.0.2.vsix
      shell: cmd

    - name: Set Qt version in Visual Studio
      run: |
        "%DEVENV_PATH2%" /command "Qt5.QtOptions.QtVersions.AddVersion?Name=6.6.1&Path=%QT_PATH%"
      shell: cmd
