name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_FILE_PATH: HelloWorld.vcxproj
  BUILD_CONFIGURATION: Debug|x64 
  DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe
  QT_PATH: ${{ github.workspace }}\ThirdParty\Qt\6.6.1\msvc2019_64
  QT_VERSION: 6.6.1
  
permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: 2022
        components: 'Desktop development with C++'

        
    - name: Debug - List repository files
      run: dir /s
      shell: cmd

    - name: Download Qt Visual Studio Tools Extension
      run: |
        Invoke-WebRequest -Uri "https://download.qt.io/development_releases/vstools/qt-vs-addin-2.6.2.vsix" -OutFile "qt-vs-addin.vsix"

    - name: Install Qt Visual Studio Tools Extension
      run: |
        $vsPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
        &"$vsPath\Common7\IDE\devenv.com" /InstallVsix qt-vs-addin.vsix

    - name: Set Qt Path in Visual Studio
      run: |
        $vsPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
        &"$vsPath\Common7\IDE\devenv.com" /command "Tools.Options"
        &"$vsPath\Common7\IDE\devenv.com" /command "QtVersions.AddQtVersion"
        &"$vsPath\Common7\IDE\devenv.com" /command "qtAddExistingVersion X:\OpenTwin\Repo\Third_Party_Libraries\Qt\6.6.1\msvc2019_64"

      
    - name: Build
      shell: cmd
      run: |
        "%DEVENV_PATH%" "%PROJECT_FILE_PATH%" /Build "%BUILD_CONFIGURATION%" /Out buildLog_Debug.txt
