name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  QT_VERSION: 6.6.1
  QT_PATH: ${{ github.workspace }}\Qt\6.6.1\msvc2019_64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Download Qt VSIX
      run: curl -L -o qt-vsaddin-msvc2022-3.0.2.vsix https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix

    - name: Install VSIX PowerShell Module
      run: |
        Install-Module -Name VSSetup -Scope CurrentUser -Force -SkipPublisherCheck

    - name: Install Qt VSIX
      run: |
        Import-Module VSSetup
        $vsixInstallerPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VSIXInstaller.exe"
        if (Test-Path $vsixInstallerPath) {
          Start-Process -Wait -FilePath $vsixInstallerPath -ArgumentList "qt-vsaddin-msvc2022-3.0.2.vsix"
        } else {
          Write-Error "VSIX Installer not found at $vsixInstallerPath"
        }

    - name: Install Qt
      run: choco install qt --version=%QT_VERSION% -y

    - name: Setup Qt Environment
      run: |
        echo "QT_PATH=${{ env.QT_PATH }}" >> $GITHUB_ENV
        echo "${{ env.QT_PATH }}\bin" >> $GITHUB_PATH
