name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  QT_VERSION: 6.6.1
  QT_PATH: ${{ github.workspace }}\Qt\6.6.1\msvc2019_64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2


    - name: Download Qt VSIX
      run: curl -L -o qt-vsaddin-msvc2022-3.0.2.vsix https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix

    - name: Install Qt VSIX
      run: |
        Start-Process -Wait -FilePath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VSIXInstaller.exe" -ArgumentList "qt-vsaddin-msvc2022-3.0.2.vsix"

    - name: Install Qt
      run: |
        choco install qt --version=%QT_VERSION% -y

    - name: Setup Qt Environment
      run: |
        echo "QT_PATH=${{ env.QT_PATH }}" >> $GITHUB_ENV
        echo "${{ env.QT_PATH }}\bin" >> $GITHUB_PATH
