name: Build Qt Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Visual Studio 2022
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Download Qt Online Installer 
      run: |
        Invoke-WebRequest -Uri "https://download.qt.io/official_releases/online_installers/qt-unified-windows-x64-online.exe" -OutFile "C:\\QtInstaller.exe"

    - name: Install Qt
      run: |
        Start-Process -FilePath "C:\\QtInstaller.exe" -ArgumentList "--silent", "--accept-messages", "--confirm-command", "install", "--auto-answer", "yes", "--default-answer", "yes", "--root", "C:\\Qt" -NoNewWindow -Wait

    - name: Set up Qt environment variables
      run: |
        $qtPath = "C:\\Qt\\6.2.4\\msvc2019_64"
        [Environment]::SetEnvironmentVariable("QTDIR", $qtPath, "Machine")
        [Environment]::SetEnvironmentVariable("PATH", $env:PATH + ";$qtPath\\bin", "Machine")

    - name: Download Qt Visual Studio Add-in
      run: |
        Invoke-WebRequest -Uri "https://download.qt.io/official_releases/vsaddin/2.6.0/qt-vsaddin-msvc2019-2.6.0.vsix" -OutFile "C:\\QtVsAddin.vsix"

    - name: Find VSIXInstaller.exe Path
      id: find-vsix
      run: |
        $vsixPath = ""
        if (Test-Path "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\VSIXInstaller.exe") {
          $vsixPath = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\VSIXInstaller.exe"
        } elseif (Test-Path "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\Common7\\IDE\\VSIXInstaller.exe") {
          $vsixPath = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\Common7\\IDE\\VSIXInstaller.exe"
        } elseif (Test-Path "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\VSIXInstaller.exe") {
          $vsixPath = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\VSIXInstaller.exe"
        } else {
          throw "VSIXInstaller.exe not found."
        }
        echo "VSIXInstaller path: $vsixPath"
        echo "VSIX_PATH=$vsixPath" >> $env:GITHUB_ENV

    - name: Install Qt Visual Studio Add-in
      run: |
        echo "Using VSIXInstaller path: $env:VSIX_PATH"
        Start-Process -FilePath $env:VSIX_PATH -ArgumentList "/quiet", "/logFile:vsixinstall.log", "C:\\QtVsAddin.vsix" -NoNewWindow -Wait

    - name: Find devenv.com Path
      id: find-devenv
      run: |
        $devenvPath = ""
        if (Test-Path "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.com") {
          $devenvPath = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.com"
        } elseif (Test-Path "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\Common7\\IDE\\devenv.com") {
          $devenvPath = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\Common7\\IDE\\devenv.com"
        } elseif (Test-Path "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.com") {
          $devenvPath = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.com"
        } else {
          throw "devenv.com not found."
        }
        echo "devenv path: $devenvPath"
        echo "DEVENV_PATH=$devenvPath" >> $env:GITHUB_ENV

    - name: Configure Qt Add-in
      run: |
        echo "Using devenv path: $env:DEVENV_PATH"
        try {
          & $env:DEVENV_PATH /command "QtVsTools.PackageUtilities, Initialize;QTVSADDIN_VERSION=6.2.3;"
        } catch {
          Write-Error "Failed to execute devenv.com command: $_"
        }

    - name: Build the project using msbuild
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 path\\to\\your\\solution.sln
