name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  QT_VERSION: 6.6.1
  QT_PATH: ${{ github.workspace }}\Qt\6.6.1\msvc2019_64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Download Qt VS Add-in
      run: |
        curl -L -o qt-vsaddin-msvc2022-3.0.2.vsix https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix
      shell: cmd

    - name: Install Qt VS Add-in with elevated permissions
      run: |
        $vsixPath = "qt-vsaddin-msvc2022-3.0.2.vsix"
        $vsixInstallerPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\vsixinstaller.exe"
        Start-Process -FilePath $vsixInstallerPath -ArgumentList "/quiet", $vsixPath -Wait -PassThru
      shell: pwsh

    - name: Create batch script to set Qt version
      run: |
        echo @echo off > set_qt_version.bat
        echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com" /command "Qt5.QtOptions.QtVersions.AddVersion?Name=6.6.1^&Path=%QT_PATH%" >> set_qt_version.bat
        echo if %%errorlevel%% neq 0 exit /b %%errorlevel%% >> set_qt_version.bat
        echo exit 0 >> set_qt_version.bat

    - name: Run batch script to set Qt version with detailed logging
      run: |
        cmd /c set_qt_version.bat > qt_version_log.txt 2> qt_version_error.txt
        type qt_version_log.txt
        type qt_version_error.txt
