name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  QT_VERSION: 6.6.1
  QT_PATH: ${{ github.workspace }}\Qt\6.6.1\msvc2019_64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2

    # Step 1: Download the Qt VS add-in
    - name: Download Qt VS add-in
      run: |
        curl -L -o qt-vsaddin-msvc2022-3.0.2.vsix https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix

    # Step 2: Install the Qt VS add-in with elevated permissions
    - name: Install Qt VS add-in
      run: |
        Start-Process -FilePath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\vsixinstaller.exe" -ArgumentList "qt-vsaddin-msvc2022-3.0.2.vsix /quiet /norestart" -Verb RunAs
      shell: powershell

    # Step 3: Set Qt version and path in Visual Studio 2022
    - name: Set Qt version in Visual Studio
      run: |
        "%DEVENV_PATH2%" /command "Qt5.QtOptions.QtVersions.AddVersion?Name=6.6.1&Path=%QT_PATH%"
      shell: cmd
