name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  QT_VERSION: 6.6.1
  DEVENV_PATH2: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
  QT_PATH: ${{ github.workspace }}\ThirdParty\Qt\6.6.1\msvc2019_64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


        
    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Download Qt VS add-in
      run: |
        curl -L -o qt-vsaddin-msvc2022-3.0.2.vsix https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix
      shell: cmd

    - name: Print Visual Studio IDE Directory
      run: |
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE"
      shell: cmd

    - name: Create Scheduled Task to Install Qt VS add-in
      run: |
        $action = New-ScheduledTaskAction -Execute "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\vsixinstaller.exe" -Argument "/quiet qt-vsaddin-msvc2022-3.0.2.vsix"
        $trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddSeconds(15)
        $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
        $task = New-ScheduledTask -Action $action -Trigger $trigger -Principal $principal
        Register-ScheduledTask -TaskName "InstallQtVSAddin" -InputObject $task
      shell: pwsh

    - name: Wait for Scheduled Task
      run: |
        Start-Sleep -Seconds 60
      shell: pwsh

    - name: Check Scheduled Task Status
      run: |
        $task = Get-ScheduledTask -TaskName "InstallQtVSAddin"
        $taskState = $task.State
        if ($taskState -ne 'Ready') {
          Get-ScheduledTaskInfo -TaskName "InstallQtVSAddin" | Select-Object -Property *
          Write-Error "Scheduled task did not complete successfully."
          exit 1
        }
      shell: pwsh

    - name: Create PowerShell script to set Qt version
      run: |
        $scriptContent = @'
        $devenvPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com"
        $qtPath = "${{ github.workspace }}\Qt\6.6.1\msvc2019_64"
        & "$devenvPath" /command "Qt5.QtOptions.QtVersions.AddVersion?Name=6.6.1&Path=$qtPath" 2>&1 | Tee-Object -FilePath qt_version_log.txt
        Write-Output "Qt version log:"
        Get-Content -Path qt_version_log.txt
        '@
        $scriptPath = "set_qt_version.ps1"
        $scriptContent | Set-Content -Path $scriptPath
      shell: pwsh

    - name: Run PowerShell script to set Qt version
      run: |
        powershell -ExecutionPolicy Bypass -File set_qt_version.ps1
      shell: cmd
