name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_FILE_PATH: HelloWorld.vcxproj
  BUILD_CONFIGURATION: Debug|x64 
  DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add Visual Studio to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Debug - List repository files
      run: dir /s
      shell: cmd
    - name: Install Qt 6.6.1
      run: |
        choco install qt --version=6.6.1 -y
      shell: cmd

    - name: Add Visual Studio to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Add Qt Path to Visual Studio 2022
      run: |
        & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find Common7\IDE\devenv.com > vsPath.txt
        set /p VS_PATH=<vsPath.txt
        call "%VS_PATH%" -command "Tools.Options" -cmdline "Qt;Versions;Add;Version name=6.6.1;Path=${{ github.workspace }}\ThirdParty\Qt\6.6.1\msvc2019_64"
      shell: cmd
    - name: Build
      shell: cmd
      run: |
        "%DEVENV_PATH%" "%PROJECT_FILE_PATH%" /Build "%BUILD_CONFIGURATION%" /Out buildLog_Debug.txt
