name: Setup Visual Studio with Qt Addin

on: [push]

jobs:
  setup-vs:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Visual Studio 2022
      run: |
        choco install visualstudio2022community --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --includeOptional"
      shell: powershell

    - name: Download Qt VS Addin
      run: |
        Invoke-WebRequest -Uri "https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix" -OutFile "qt-vsaddin-msvc2022-3.0.2.vsix"
      shell: powershell

    - name: Install Qt VS Addin
      run: |
        Start-Process -FilePath "qt-vsaddin-msvc2022-3.0.2.vsix" -ArgumentList "/quiet" -Wait
      shell: powershell

    - name: Integrate Qt Addin to Visual Studio 2022
      run: |
        & "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe" /setup
      shell: powershell
