name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_FILE_PATH: HelloWorld.vcxproj
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add Visual Studio to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Find Visual Studio
      id: vs
      run: |
        vswhere -products * -requires Microsoft.Component.MSBuild -property installationPath -latest > vs_path.txt
        echo "::set-output name=vs_path::$(cat vs_path.txt)"

    - name: Debug - List repository files
      run: dir /s
      shell: cmd

    - name: Build
      shell: cmd
      run: |
        "%{steps.vs.outputs.vs_path}\Common7\IDE\devenv.com" "%PROJECT_FILE_PATH%" /Build "%BUILD_CONFIGURATION%"
