
name: Qt VS Add-in Setup (Windows)

on:
  push: # Trigger the workflow on pushes

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Checkout the repository code

      - name: Setup MSBuild and Visual Studio
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '17.0' # Visual Studio 2022

      - name: Download Qt VS Add-in (version 3.0.2)
        run: |
          echo "Downloading Qt VS Add-in..."
          curl -L -o qt-vsaddin-msvc2022-3.0.2.vsix https://download.qt.io/development_releases/vsaddin/3.0.2/qt-vsaddin-msvc2022-3.0.2.vsix


      - name: Install Qt VS add-in
        run: |
            $vsixPaths = @(
              "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\VSIXInstaller.exe",
              "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\Common7\\IDE\\VSIXInstaller.exe",
              "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\VSIXInstaller.exe"
            )
    
            $vsixPath = $vsixPaths | Where-Object { Test-Path $_ }
    
            if (-not $vsixPath) {
              Write-Error "VSIXInstaller.exe not found in any of the expected paths."
              exit 1
            }
    
            Write-Output "Using VSIXInstaller at path: $vsixPath"
    
            Start-Process -FilePath $vsixPath -ArgumentList "/quiet", "/logFile:vsixinstall.log", "qt-vsaddin-msvc2022-3.0.2.vsix" -NoNewWindow -Wait
        shell: powershell


       
             
      - name: Verify Installation
        shell: powershell
        run: |
          echo "Verifying Qt VS Add-in installation..."
          $devenvPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe"
          if (-not (Test-Path $devenvPath)) {
            throw "devenv.exe not found at $devenvPath."
          }
          & "$devenvPath" /setup
