name: Build and Test

on: [push, pull_request]

env:
  PROJECT_FILE_PATH: HelloWorld.vcxproj
  BUILD_CONFIGURATION: Debug|x64
  DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout DemoCI repository
      uses: actions/checkout@v4
      with:
        repository: Reeva30/DemoCI
        ref: Test
        path: DemoCI

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/'
        install-deps: 'true'
        modules: 'qtcharts qtwebengine'
        archives: 'qtbase qtsvg'
        cache: 'false'
        cache-key-prefix: 'install-qt-action'
        setup-python: 'true'
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        set-env: 'true'
        tools-only: 'false'
        aqtversion: '==3.1.*'

    - name: List root directory contents
      run: dir "${{ github.workspace }}\QT"

    - name: List QT directory contents
      run: dir "${{ github.workspace }}\QT\5.15.2"

    - name: List Tools directory contents
      run: dir "${{ github.workspace }}\QT\Tools"

    - name: List QtCreator directory contents
      run: dir "${{ github.workspace }}\QT\Tools\QtCreator\bin"

    - name: Set up Qt environment variables
      run: |
        echo "Setting up Qt environment variables"
        echo "QT_HOME=${{ github.workspace }}\QT" >> $GITHUB_ENV
        echo "QTDIR=${{ github.workspace }}\QT\5.15.2" >> $GITHUB_ENV
        echo "QT_PLUGIN_PATH=${{ github.workspace }}\QT\5.15.2\plugins" >> $GITHUB_ENV
        echo "QML2_IMPORT_PATH=${{ github.workspace }}\QT\5.15.2\qml" >> $GITHUB_ENV
        echo "QTDIR=${{ github.workspace }}/DemoCI/QTMSBuild" >> $GITHUB_ENV
        echo "QtMsBuild=${{ github.workspace }}/DemoCI/QTMSBuild" >> $GITHUB_ENV
        echo "Path=${{ github.workspace }}\QT\5.15.2\bin;${{ github.workspace }}/DemoCI/QTMSBuild;$Env:Path" >> $GITHUB_ENV

    - name: Build the solution with devenv.com
      run: |
        echo "Building the solution using devenv.com"
        &"${{ env.DEVENV_PATH }}" "${{ github.workspace }}\${{ env.PROJECT_FILE_PATH }}" /Build "${{ env.BUILD_CONFIGURATION }}"

    - name: Run tests
      run: |
        echo "Running tests using devenv.com"
        &"${{ env.DEVENV_PATH }}" "${{ github.workspace }}\${{ env.PROJECT_FILE_PATH }}" /RunTests
