name: Build Qt C++ Project

on:
  push:
    branches:
      - m
  pull_request:
    branches:
      - m

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; `
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Qt
      run: |
        choco install qt5 --version=5.15.2 -y

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Project
      env:
        QT_DIR: C:\Qt\5.15.2\msvc2019_64
      run: |
        $env:Path += ";$env:QT_DIR\bin"
        devenv.exe <your_solution_file>.sln /Build "Release"
