name: Build Qt Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Visual Studio 2022
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install Chocolatey
      run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Qt Visual Studio Tools
      run: |
        choco install qtvisualstudiotools --pre || echo "Qt Visual Studio Tools installation failed"

    - name: Install Qt
      run: |
        choco install qt --version=6.2.3

    - name: Set up Qt environment variables
      run: |
        $qtPath = "C:\Qt\6.2.3\msvc2019_64"
        [Environment]::SetEnvironmentVariable("QTDIR", $qtPath, "Machine")
        [Environment]::SetEnvironmentVariable("PATH", $env:PATH + ";$qtPath\bin", "Machine")

    - name: Configure Qt Add-in
      run: |
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.com" /command "QtVsTools.PackageUtilities, Initialize;QTVSADDIN_VERSION=6.2.3;"

    - name: Build the project using msbuild
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 path\to\your\solution.sln
